<?php

use Illuminate\Database\Seeder;
Use App\Materia;

class MateriasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Materia::create(['id'=>1,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>2,'materia'=>'Tecnología de la Imagen','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>3,'materia'=>'Elementos de Audio','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>4,'materia'=>'Taller de Lectura y Escritura profesional','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>5,'materia'=>'Educación Auditiva','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>6,'materia'=>'Electrónica de las Comunicaciones','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>7,'materia'=>'Lenguaje Audiovisual 1','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>8,'materia'=>'Registro de Sonido en Audiovisuales','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>9,'materia'=>'Montaje 1','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>10,'materia'=>'Fotografía e Iluminación en Audiovisuales','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>11,'materia'=>'Inglés I','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>12,'materia'=>'Lenguaje Audiovisual 2','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>13,'materia'=>'Audición y Análisis Musical','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>14,'materia'=>'Taller de Edición de Sonido','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>15,'materia'=>'Seminario de Pensamiento Nacional y Latinoamericano','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>16,'materia'=>'Taller de Montaje','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>17,'materia'=>'Realización Integral Audiovisual 1','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>18,'materia'=>'Arte y Sociedad','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>19,'materia'=>'Guión','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>20,'materia'=>'Taller de Composición Sonora','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>21,'materia'=>'Seminario de Justicia y Derechos Humanos','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>22,'materia'=>'Banda Sonora','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>23,'materia'=>'Géneros Estilos Audiovisuales','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>24,'materia'=>'Taller de Experimentación Audiovisual','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>25,'materia'=>'Realización Integral Audiovisual 2','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>26,'materia'=>'Ética Profesional','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>27,'materia'=>'Gestión de proyectos Audiovisuales','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>28,'materia'=>'Estética','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>29,'materia'=>'Comunicación Audiovisual','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>30,'materia'=>'Tecnología de Postproducción 1','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>31,'materia'=>'Imagen, Tipografía e Identidad Cultural','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>32,'materia'=>'Acústica','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>33,'materia'=>'Organología','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>34,'materia'=>'Semiótica','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>35,'materia'=>'Inglés II','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>36,'materia'=>'Metodología de Investigación','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>37,'materia'=>'Optativa 1','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>38,'materia'=>'Edición y Corrección Digital de Imagen','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>39,'materia'=>'Tecnología de Postproducción 2','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>40,'materia'=>'Montaje 2','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>41,'materia'=>'Animación 3D 1','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>42,'materia'=>'Composición Digital','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>43,'materia'=>'Tecnología de Postproducción 3','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>44,'materia'=>'Masterización y Postproducción 1','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>45,'materia'=>'Sistemas de Electroacústica','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>46,'materia'=>'Taller de Grabación 1','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>47,'materia'=>'Masterización y Postproducción 2','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>48,'materia'=>'Taller de Grabación 2','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>49,'materia'=>'Alineación y Operación de sistemas de Amplificación','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>50,'materia'=>'Optativa 2','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>51,'materia'=>'Optativa 3','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>52,'materia'=>'Taller de Trabajo Final Integrador Mención Postproducción de Imagen','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>53,'materia'=>'Animación 3D 2','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>54,'materia'=>'Taller de Postproducción de Imagen','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>55,'materia'=>'Práctica Preprofesional Mención Postproducción de Imagen','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>56,'materia'=>'Taller de Postproducción de Sonido en Audiovisuales','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>57,'materia'=>'Audioanalisis','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>58,'materia'=>'Taller de Trabajo Final Integrador Mención Sonido y Grabación','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>59,'materia'=>'Práctica Preprofesional Mención Sonido y Grabación','general'=>0,'carrera_id'=>1]);
Materia::create(['id'=>60,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>61,'materia'=>'Sociología Política','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>62,'materia'=>'Fundamentos de Ciencia Política','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>63,'materia'=>'Economía Política','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>64,'materia'=>'Historia moderna y contemporánea','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>65,'materia'=>'Instituciones del derecho','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>66,'materia'=>'Seminario de Pensamiento Nacional y Latinoamericano','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>67,'materia'=>'Estadística social','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>68,'materia'=>'Teoría Política I','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>69,'materia'=>'Metodología de la investigación social I','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>70,'materia'=>'Teoría Política II','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>71,'materia'=>'Derecho Constitucional','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>72,'materia'=>'Fundamentos de Macroeconomía','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>73,'materia'=>'Historia política y social latinoamericana','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>74,'materia'=>'Metodología de la Investigación Social II','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>75,'materia'=>'Teoría del Estado','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>76,'materia'=>'Economía internacional','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>77,'materia'=>'Historia política y social argentina','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>78,'materia'=>'Taller de práctica pre-profesional - 1º etapa','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>79,'materia'=>'Política internacional','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>80,'materia'=>'Análisis de la sociedad argentina','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>81,'materia'=>'Derecho administrativo','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>82,'materia'=>'Teoría política contemporánea','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>83,'materia'=>'Adminstración pública','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>84,'materia'=>'Economía de gobierno y finanzas públicas','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>85,'materia'=>'Gobierno local','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>86,'materia'=>'Políticas públicas','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>87,'materia'=>'Análisis político y opinión pública','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>88,'materia'=>'Seminario de Justicia y Derechos Humanos','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>89,'materia'=>'Planificación estratégica y análisis de politicas públicas','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>90,'materia'=>'Formulación y evaluación de proyectos','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>91,'materia'=>'Ideas políticas en América Latina','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>92,'materia'=>'Política comparada','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>93,'materia'=>'Política Latinoamericana','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>94,'materia'=>'Comunicación política','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>95,'materia'=>'Seminario optativo I','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>96,'materia'=>'Seminario optativo II','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>97,'materia'=>'Informática Modúlo 2: Procesador de textos','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>98,'materia'=>'Informática Modúlo 7: Sistemas de información geográfica','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>99,'materia'=>'Informática Modúlo 11: Programa estadístico para las Ciencias Sociales 1','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>100,'materia'=>'Informática Modúlo 12: Programa estadístico para las Ciencias Sociales 2','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>101,'materia'=>'Inglés I','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>102,'materia'=>'Inglés II','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>103,'materia'=>'Inglés III','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>104,'materia'=>'Taller de práctica pre-profesional - 2º etapa','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>105,'materia'=>'Taller de trabajo final integrador','general'=>0,'carrera_id'=>2]);
Materia::create(['id'=>106,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>107,'materia'=>'Matemática I','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>108,'materia'=>'Química general','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>109,'materia'=>'Física I','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>110,'materia'=>'Biología','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>111,'materia'=>'Matemática II','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>112,'materia'=>'Química inorgánica','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>113,'materia'=>'Física II','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>114,'materia'=>'Anatomía y Fisiología','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>115,'materia'=>'Microbiología general','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>116,'materia'=>'Química orgánica','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>117,'materia'=>'Matemática III','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>118,'materia'=>'Fisicoquímica y biofísica','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>119,'materia'=>'Química analítica','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>120,'materia'=>'Química biológica','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>121,'materia'=>'Bromatología I','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>122,'materia'=>'Industría y Tecnología de los Alimentos I','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>123,'materia'=>'Microbiología de Alimentos I','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>124,'materia'=>'Estadística y Bioestadística','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>125,'materia'=>'Nutrición','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>126,'materia'=>'Bromatología II','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>127,'materia'=>'Industría y Tecnología de los Alimentos II','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>128,'materia'=>'Equipos e Instalaciones I','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>129,'materia'=>'Microbiología de los Alimentos II','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>130,'materia'=>'Toxicología','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>131,'materia'=>'Bromatología III','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>132,'materia'=>'Industría y Tecnología de los Alimentos III','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>133,'materia'=>'Historia, Legislación y Ética Profesional','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>134,'materia'=>'Práctica Preprofesional (Bromatología)','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>135,'materia'=>'Equipos e instalaciones II','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>136,'materia'=>'Calidad','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>137,'materia'=>'Conservación y empaque','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>138,'materia'=>'Instrumentación y Automatización','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>139,'materia'=>'Industría y Tecnología de los Alimentos IV','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>140,'materia'=>'Economía y Gestión Empresaria','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>141,'materia'=>'Formulación de proyectos industriales','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>142,'materia'=>'Integración de la Industria Alimentaria','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>143,'materia'=>'Industria alimenticia y medio ambiente','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>144,'materia'=>'Industria y tecnología de los Alimentos V','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>145,'materia'=>'Educación y Fiscalización','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>146,'materia'=>'Trabajo Final','general'=>0,'carrera_id'=>3]);
Materia::create(['id'=>147,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>148,'materia'=>'Taller de Diseño Industrial I (Formación Básica)','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>149,'materia'=>'Tecnología, Materiales y Procesos I (Formación Básica)','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>150,'materia'=>'Desarrollos Visuales','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>151,'materia'=>'Dibujo Técnico','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>152,'materia'=>'Taller de Diseño Industrial II (Orientación maquinaria, equipos y vehículos)','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>153,'materia'=>'Tecnología, Materiales y Procesos II (Orientación maquinaria, equipos y vehículos)','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>154,'materia'=>'Morfología','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>155,'materia'=>'Representación Digital','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>156,'materia'=>'Taller de Lectura y Escritura Profesional','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>157,'materia'=>'Métodos del Diseño','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>158,'materia'=>'Taller de Diseño Industrial III (Orientación maquinaria, equipos y vehículos)','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>159,'materia'=>'Tecnología, Materiales y Procesos III (Orientación maquinaria, equipos y vehículos)','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>160,'materia'=>'Modelado Digital (Orientación maquinaria, equipos y vehículos)','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>161,'materia'=>'Ciencia Aplicada al Diseño Industrial','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>162,'materia'=>'Historia Social del Diseño I','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>163,'materia'=>'Taller de Práctica Pre Profesional','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>164,'materia'=>'Idioma Extranjero Nivel I','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>165,'materia'=>'Seminario de Justicia y Derechos Humanos','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>166,'materia'=>'Seminario de Pensamiento Nacional y Latinoamericano','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>167,'materia'=>'Taller de Diseño Industrial IV (Orientación Transportes)','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>168,'materia'=>'Tecnología, Materiales y Procesos IV (Orientación Transportes)','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>169,'materia'=>'Semiótica Aplicada al Diseño Industrial','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>170,'materia'=>'Manufactura Digital (Orientación Transportes)','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>171,'materia'=>'Historia Social del Diseño II','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>172,'materia'=>'Taller de Diseño Industrial V (Orientación Transportes)','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>173,'materia'=>'Desarrollos Científico, Tecnológico e Innovación Productiva','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>174,'materia'=>'Metodología de la Investigación','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>175,'materia'=>'Diseño Sustentable','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>176,'materia'=>'Etica y Legislación Profesional','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>177,'materia'=>'Taller de Trabajo Integrador Final','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>178,'materia'=>'Idioma Extranjero Nivel II','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>179,'materia'=>'Optativa (Dto. de Desarrollo Productivo. Licenciatura en Economía Empresarial)','general'=>0,'carrera_id'=>4]);
Materia::create(['id'=>180,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>181,'materia'=>'Taller de Diseño I','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>182,'materia'=>'Geometría descriptiva aplicada','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>183,'materia'=>'Medios Expresivos I','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>184,'materia'=>'Espacio Tipográfico I','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>185,'materia'=>'Teoría del Diseño I','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>186,'materia'=>'Lectura y Escritura Profesional','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>187,'materia'=>'Tecnología I','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>188,'materia'=>'Computación I','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>189,'materia'=>'Medios Expresivos II','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>190,'materia'=>'Taller de Diseño II','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>191,'materia'=>'Espacio Tipográfico II','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>192,'materia'=>'Historia de la Comunicación visual','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>193,'materia'=>'Metodología de la Investigación','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>194,'materia'=>'Taller de Diseño III','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>195,'materia'=>'Tecnología II','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>196,'materia'=>'Computación II','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>197,'materia'=>'Fotografía','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>198,'materia'=>'Medios Expresivos III','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>199,'materia'=>'Espacio Tipográfico III','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>200,'materia'=>'Historia Social del Diseño','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>201,'materia'=>'Taller de Diseño IV','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>202,'materia'=>'Computación III','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>203,'materia'=>'Taller de Diseño Orientado','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>204,'materia'=>'Comunicación','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>205,'materia'=>'Teoría del Diseño II','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>206,'materia'=>'Semiótica','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>207,'materia'=>'Video','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>208,'materia'=>'Taller de Trabajo Final Integrador','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>209,'materia'=>'Práctica Pre Profesional','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>210,'materia'=>'Estética','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>211,'materia'=>'Ética profesional','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>212,'materia'=>'Taller de Trabajo Final Integrador','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>213,'materia'=>'Idioma Extranjero I','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>214,'materia'=>'Idioma Extranjero II','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>215,'materia'=>'Seminario de Pensamiento Nacional y Latinoamericano','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>216,'materia'=>'Seminario de Justicia y Derechos Humanos','general'=>0,'carrera_id'=>5]);
Materia::create(['id'=>217,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>218,'materia'=>'Historia Económica Contemporánea','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>219,'materia'=>'Contabilidad','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>220,'materia'=>'Introducción a la Matemática','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>221,'materia'=>'Taller de Producción de Textos de Economía y Administración','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>222,'materia'=>'Economía y Sociedad','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>223,'materia'=>'Organización y Gestión','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>224,'materia'=>'Elementos de Matemática','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>225,'materia'=>'Microeconomía','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>226,'materia'=>'Derecho Comercial','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>227,'materia'=>'Cálculo Financiero y Desarrollo Estadístico Aplicado','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>228,'materia'=>'Macroeconomía','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>229,'materia'=>'Costos Empresariales','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>230,'materia'=>'Derecho Tributario','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>231,'materia'=>'Organización de la Producción y la Tecnología','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>232,'materia'=>'Control de Gestión','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>233,'materia'=>'Macroeconomía y Política Económica','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>234,'materia'=>'Comercialización','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>235,'materia'=>'Derecho del Trabajo y de la Seguridad Social','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>236,'materia'=>'Comercio Exterior y Economía Internacional','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>237,'materia'=>'Financiamiento','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>238,'materia'=>'Plan de Negocios','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>239,'materia'=>'Taller de Integración I','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>240,'materia'=>'Formulación y Evaluación de Proyectos','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>241,'materia'=>'Gestión Ambiental y Empresa','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>242,'materia'=>'Sistemas de organización','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>243,'materia'=>'Economía bancaria y financiera','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>244,'materia'=>'Administración de los Recursos Humanos','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>245,'materia'=>'Economía Industrial','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>246,'materia'=>'Taller de Integración II','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>247,'materia'=>'Inglés I','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>248,'materia'=>'Informática: Módulo 8 - Gestión de proyectos','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>249,'materia'=>'Informática: Módulo 11 - Programa Estadístico para las Ciencias Sociales I','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>250,'materia'=>'Seminario de Justicia y Derechos Humanos','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>251,'materia'=>'Seminario de Pensamiento Nacional y Latinoamericano','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>252,'materia'=>'Problemas actuales de la economía argentina','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>253,'materia'=>'Ética y Empresa','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>254,'materia'=>'Mediación y Negociación','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>255,'materia'=>'Políticas y Estrategias para el Desarrollo Regional y Local','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>256,'materia'=>'Taller de Trabajo Final Integrador','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>257,'materia'=>'Seminario: Responsabilidad Social Empresaria','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>258,'materia'=>'Planeamiento Estratégico y Toma de Decisiones','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>259,'materia'=>'Seminario Economía Social','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>260,'materia'=>'Práctica Pre-profesional','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>261,'materia'=>'Inglés II','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>262,'materia'=>'Módulo de Informática opcional A','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>263,'materia'=>'Módulo de Informática opcional B','general'=>0,'carrera_id'=>6]);
Materia::create(['id'=>264,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>265,'materia'=>'Psicología de la Educación','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>266,'materia'=>'Taller "Las Instituciones Educativas"','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>267,'materia'=>'Filosofía de la Educación','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>268,'materia'=>'Política, Estado y Educación','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>269,'materia'=>'Teorías del Aprendizaje','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>270,'materia'=>'Historía de la Educación Argentina y Latinoamericana','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>271,'materia'=>'Economía de la Educación','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>272,'materia'=>'Sociología de la Educación','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>273,'materia'=>'Administración y Gestión I','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>274,'materia'=>'Teoría Curricular','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>275,'materia'=>'Teorías Pedagógicas','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>276,'materia'=>'Infancia y Juventud','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>277,'materia'=>'Administración y Gestión II (Incluye 32 hs. de tareas de prácticas de campo)','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>278,'materia'=>'Didáctica I','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>279,'materia'=>'Talleres "Las TIC en Educación"','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>280,'materia'=>'Adultos Mayores','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>281,'materia'=>'Niveles y Modalidades del Sistema educativo argentino','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>282,'materia'=>'Investigación Educativa I','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>283,'materia'=>'Didáctica II (Incluye 32 hs. de prácticas docentes)','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>284,'materia'=>'Seminario de Pensamiento Nacional y Latinoamericano','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>285,'materia'=>'Nuevos Modelos Universitarios','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>286,'materia'=>'Seminario de Justicia y Derechos Humanos','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>287,'materia'=>'Investigación Educativa II','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>288,'materia'=>'Sistemas Educativos Comparados','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>289,'materia'=>'Políticas Públicas en Educación','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>290,'materia'=>'Formulación de proyectos de Formación profesional y Capacitación Laboral','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>291,'materia'=>'Ateneo I','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>292,'materia'=>'Prácticas Profesionales (incluye 32 hs. de prácticas fuera del aula)','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>293,'materia'=>'Ateneo II','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>294,'materia'=>'Seminario Optativo I','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>295,'materia'=>'Seminario Optativo II','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>296,'materia'=>'Seminario Optativo III','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>297,'materia'=>'Seminario Optativo IV','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>298,'materia'=>'Seminario Optativo V','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>299,'materia'=>'Taller de Trabajo Final (incluye 32 hs de tutorías personalizadas)','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>300,'materia'=>'Inglés I','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>301,'materia'=>'Inglés II','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>302,'materia'=>'Taller de Inglés para Educación','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>303,'materia'=>'Informática Módulo a elección ','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>304,'materia'=>'Informática Módulo a elección ','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>305,'materia'=>'Informática Módulo 14. Formación de usuarios de la Biblioteca Rodolfo Puiggrós','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>306,'materia'=>'Informática Módulo 15. Bibliotecas digitales y acceso a sistemas de información académica.','general'=>0,'carrera_id'=>7]);
Materia::create(['id'=>307,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>308,'materia'=>'Introducción a la problemática urbana','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>309,'materia'=>'Ambiente I','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>310,'materia'=>'Geografía urbana','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>311,'materia'=>'Introducción al desarrollo sustentable','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>312,'materia'=>'Taller de ciencias aplicadas al ambiente','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>313,'materia'=>'Técnicas en cartografía y fotointerpretación','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>314,'materia'=>'Principios de administración y gestión','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>315,'materia'=>'Matemática y estadística aplicada a estudios ambientales','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>316,'materia'=>'Sociología ambiental','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>317,'materia'=>'Ciudad y territorio','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>318,'materia'=>'Ambiente II','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>319,'materia'=>'Taller de investigación urbana','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>320,'materia'=>'Economía y desarrollo sustentable I','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>321,'materia'=>'Teledetección y sistemas de información geográfica','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>322,'materia'=>'Educación ambiental','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>323,'materia'=>'Procesos urbanos I','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>324,'materia'=>'Fundamentos de ecología','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>325,'materia'=>'Procesos de Evaluación de Impactos Ambientales','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>326,'materia'=>'Legislación Ambiental','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>327,'materia'=>'Ambiente III','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>328,'materia'=>'Economía y Desarrollo Sustentable II','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>329,'materia'=>'Práctica Pre-Profesional','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>330,'materia'=>'Gestión Administrativa Municipal Ambiental','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>331,'materia'=>'Procesos Urbanos II','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>332,'materia'=>'Redes I: Movilidad urbana','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>333,'materia'=>'Seminario optativo I','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>334,'materia'=>'Inglés I','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>335,'materia'=>'Inglés II','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>336,'materia'=>'Informática Módulo 3: Planilla de Cálculo 1','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>337,'materia'=>'Informática Módulo 4: Planilla de Cálculo 2','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>338,'materia'=>'Seminario de Justicia y Derechos Humanos','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>339,'materia'=>'Seminario de Pensamiento Nacional y Latinoamericano','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>340,'materia'=>'Política Ambiental en Argentina y Mercosur','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>341,'materia'=>'Procesos de Producción del Hábitat','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>342,'materia'=>'Ambiente IV','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>343,'materia'=>'Formulación y Gestión de proyectos Urbano-Ambientales','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>344,'materia'=>'Gestión Ambiental y Empresa','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>345,'materia'=>'Procesos urbanos III','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>346,'materia'=>'Redes II: Servicios y saneamiento urbano','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>347,'materia'=>'Seminario optativo II','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>348,'materia'=>'Auditoría Ambiental','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>349,'materia'=>'Financiamiento y Evaluación de Proyectos Urbano - Ambientales','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>350,'materia'=>'Negociación y Mediación','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>351,'materia'=>'Seminario optativo III','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>352,'materia'=>'Seminario optativo IV','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>353,'materia'=>'Práctica Preprofesional','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>354,'materia'=>'Inglés III','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>355,'materia'=>'Informática Módulo 8: Gestión de Proyectos','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>356,'materia'=>'Informática Módulo 9: Diseño de objetos en 3D','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>357,'materia'=>'Taller de Trabajo Final Integrador','general'=>0,'carrera_id'=>9]);
Materia::create(['id'=>358,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>359,'materia'=>'Introducción a la Teoría del Estado','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>360,'materia'=>'Instituciones del Derecho','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>361,'materia'=>'Historia argentina y derechos humanos','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>362,'materia'=>'Derecho Constitucional y constitucionalismo social','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>363,'materia'=>'Configuración histórica de los derechos humanos en América Latina I','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>364,'materia'=>'Derechos Humanos y Comunicación','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>365,'materia'=>'Educación y TIC en Derechos Humanos','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>366,'materia'=>'Derechos Humanos y Soberanía','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>367,'materia'=>'Metodología de la investigación social I','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>368,'materia'=>'Teoría Política','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>369,'materia'=>'Configuración histórica de los derechos humanos en América Latina II','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>370,'materia'=>'Derecho Penal','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>371,'materia'=>'Historia política, social y cultural latinoamericana','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>372,'materia'=>'Problemas actuales de acceso a la justicia','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>373,'materia'=>'Derechos sociales, económicos y culturales','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>374,'materia'=>'Políticas Públicas y políticas en organizaciones sociales','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>375,'materia'=>'Psicología Social','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>376,'materia'=>'Estrategias de formación, capacitación y promoción','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>377,'materia'=>'Seminario de Pensamiento Nacional y Latinoamericano','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>378,'materia'=>'Informática Módulo 2','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>379,'materia'=>'Informática Módulo 7','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>380,'materia'=>'Informática Módulo 11','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>381,'materia'=>'Informática Módulo 12','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>382,'materia'=>'Inglés I','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>383,'materia'=>'Inglés II','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>384,'materia'=>'Inglés III','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>385,'materia'=>'Taller de práctica pre profesional I','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>386,'materia'=>'Taller de integración','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>387,'materia'=>'Sociología del derecho','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>388,'materia'=>'Los derechos sociales en las políticas públicas','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>389,'materia'=>'Análisis de políticas públicas','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>390,'materia'=>'Derechos humanos y derechos sociales en Latinoamérica','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>391,'materia'=>'Protección internacional de derechos humanos','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>392,'materia'=>'Política Contemporánea Latinoamericana','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>393,'materia'=>'Metodología de la investigación social II','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>394,'materia'=>'Elementos básicos de los procesos judiciales','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>395,'materia'=>'Introducción al Sistema Judicial Argentino','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>396,'materia'=>'Formulación y evaluación de proyectos','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>397,'materia'=>'Filosofía del Derecho y teoría de la Justicia','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>398,'materia'=>'Democracia y Derechos Humanos','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>399,'materia'=>'Seminario Optativo I','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>400,'materia'=>'Seminario Optativo II','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>401,'materia'=>'Seminario Optativo III','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>402,'materia'=>'Taller de práctica pre profesional II','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>403,'materia'=>'Taller de Trabajo Final Integrador','general'=>0,'carrera_id'=>10]);
Materia::create(['id'=>404,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>405,'materia'=>'Salud Colectiva','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>406,'materia'=>'Anatomía y Fisiología','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>407,'materia'=>'Seminario de Situaciones Problemáticas y Territorio','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>408,'materia'=>'Seminario de Introducción a las Problemáticas Alimentarias','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>409,'materia'=>'Nutrición I','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>410,'materia'=>'Biofísica y Bioquímica I','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>411,'materia'=>'Salud Mental','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>412,'materia'=>'Nutrición II','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>413,'materia'=>'Física y Química Culinaria (Técnica dietética)','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>414,'materia'=>'Antropología','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>415,'materia'=>'Seminario optativo I','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>416,'materia'=>'Evaluación Nutricional','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>417,'materia'=>'Biofísica y Bioquímica II','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>418,'materia'=>'Nutrición III (Nutrición infanto-juvenil)','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>419,'materia'=>'Educación Alimentaria Nutricional','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>420,'materia'=>'Bromatología y Tecnología de los Alimentos I','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>421,'materia'=>'Microbiología y Parasitología','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>422,'materia'=>'Ética Profesional','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>423,'materia'=>'Nutrición IV (Nutrición en la adolescencia, adultez y actividad física)','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>424,'materia'=>'Promoción Comunitaria','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>425,'materia'=>'Economía Regional y Alimentaria','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>426,'materia'=>'Bromatología y Tecnología de los Alimentos II','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>427,'materia'=>'Nutrición Comunitaria','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>428,'materia'=>'Desarrollo Comunitario y Organización Social','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>429,'materia'=>'Seminario Optativo II','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>430,'materia'=>'Epidemiología I','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>431,'materia'=>'Prácticas en Nutrición Comunitaria','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>432,'materia'=>'Idioma extranjero Nivel I (Inglés I - Portugués I)','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>433,'materia'=>'Seminario de Pensamiento Nacional y Latinoamericano','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>434,'materia'=>'Seminario de Justicia y Derechos Humanos','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>435,'materia'=>'Informática - Módulo III: Planilla de cálculo I','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>436,'materia'=>'Informática - Módulo IV: Planilla de cálculo II','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>437,'materia'=>'Núcleo Clínico Integrado: Fisiopatología, Dietoterapia del Adulto y Técnica Dietoterápica','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>438,'materia'=>'Metodología de Investigación','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>439,'materia'=>'Epidemiología II','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>440,'materia'=>'Gestión y Administración de Servicios de Alimentación','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>441,'materia'=>'Gestión de las Organizaciones de Salud','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>442,'materia'=>'Fisiopatología y Dietoterapia del Niño','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>443,'materia'=>'Prácticas en Salud Colectiva','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>444,'materia'=>'Taller de Trabajo Final Integrador','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>445,'materia'=>'Prácticas en Dietoterapia y Gestión y Administración de Servicios de Alimentación','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>446,'materia'=>'Seminario Optativo III','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>447,'materia'=>'Seminario Optativo IV','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>448,'materia'=>'Idioma extranjero Nivel II (Inglés II - Portugués II)','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>449,'materia'=>'Informática Módulo específico Antropometría','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>450,'materia'=>'Informática Módulo específico Epidemiología','general'=>0,'carrera_id'=>11]);
Materia::create(['id'=>451,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>452,'materia'=>'Historia Moderna y Contemporánea I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>453,'materia'=>'Historia Argentina I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>454,'materia'=>'Lógica y Epistemología de las Ciencias Sociales','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>455,'materia'=>'Introducción a las Relaciones Internacionales','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>456,'materia'=>'Pensamiento Filosófico','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>457,'materia'=>'Inglés I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>458,'materia'=>'Historia Moderna y Contemporánea II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>459,'materia'=>'Historia Argentina II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>460,'materia'=>'Metodología de la Investigación en Ciencias Sociales','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>461,'materia'=>'Filosofía Moderna y Contemporánea','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>462,'materia'=>'Economía Política I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>463,'materia'=>'Inglés II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>464,'materia'=>'Historia de las Relaciones Internacionales','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>465,'materia'=>'Economía Política II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>466,'materia'=>'Sistemática de la Ciencia Política','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>467,'materia'=>'Métodos y Técnicas de Investigación Aplicados','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>468,'materia'=>'Pensamiento Clásicos de las Relaciones Internacionales','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>469,'materia'=>'Inglés III','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>470,'materia'=>'Teoría de las Relaciones Internacionales I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>471,'materia'=>'Teoría Política I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>472,'materia'=>'Economía Política Internacional I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>473,'materia'=>'Política Internacional Contemporánea','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>474,'materia'=>'Diseño y Formulación de Modelos Prospectivos y de Investigación','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>475,'materia'=>'Portugués I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>476,'materia'=>'Economía Política Internacional II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>477,'materia'=>'Teoría de las Relaciones Internacionales II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>478,'materia'=>'Sistemas Políticos Comparados','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>479,'materia'=>'Política Exterior Argentina I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>480,'materia'=>'Historia de las Relaciones Internacionales Latinoamericanas','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>481,'materia'=>'Portugués II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>482,'materia'=>'Derecho e Instituciones Internacionales','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>483,'materia'=>'Agenda Internacional','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>484,'materia'=>'Teoría Política II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>485,'materia'=>'Seminario de Justicia y Derechos Humanos','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>486,'materia'=>'Política Exterior Argentina II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>487,'materia'=>'Módulo de Informática 11: Programa Estadístico para las Ciencias Sociales I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>488,'materia'=>'Seminario de Pensamiento Nacional y Latinoamericano','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>489,'materia'=>'Módulo de Informática 12: Programa Estadístico para las Ciencias Sociales II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>490,'materia'=>'Procesos de Integración Americanos','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>491,'materia'=>'Taller de Trabajo Final Integrador I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>492,'materia'=>'Sistemas Políticos Latinoamericanos Comparados','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>493,'materia'=>'Prospectiva Estratégica','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>494,'materia'=>'Política Doméstica y Externa Brasileña','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>495,'materia'=>'Taller de Trabajo Final Integrador II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>496,'materia'=>'Políticas Exteriores Latinoamericanas Comparadas','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>497,'materia'=>'Seminario Optativo I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>498,'materia'=>'Seminario Optativo II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>499,'materia'=>'Seminario Optativo III','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>500,'materia'=>'Seminario Optativo IV','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>501,'materia'=>'Seminario Atlántico Sur, Malvinas y Antártida','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>502,'materia'=>'Taller de Prácticas Pre-profesionales','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>503,'materia'=>'Módulo de Informática 12: Programa Estadístico para las Ciencias Sociales II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>504,'materia'=>'Procesos de Integración Americanos','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>505,'materia'=>'Taller de Trabajo Final Integrador I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>506,'materia'=>'Teoría de la Integración','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>507,'materia'=>'Prospectiva Estratégica','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>508,'materia'=>'Derecho de la Integración','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>509,'materia'=>'Taller de Trabajo Final Integrador II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>510,'materia'=>'Economía Contemporánea Brasileña','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>511,'materia'=>'Seminario Optativo I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>512,'materia'=>'Seminario Optativo II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>513,'materia'=>'Seminario Optativo III','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>514,'materia'=>'Seminario Optativo IV','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>515,'materia'=>'Seminario Atlántico Sur, Malvinas y Antártida','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>516,'materia'=>'Taller de Prácticas Pre-profesionales','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>517,'materia'=>'Módulo de Informática 12: Programa Estadístico para las Ciencias Sociales II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>518,'materia'=>'Defensa Nacional','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>519,'materia'=>'Taller de Trabajo Final Integrador I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>520,'materia'=>'Seguridad Internacional','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>521,'materia'=>'Prospectiva Estratégica','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>522,'materia'=>'Geopolítica y Análisis Estratégico','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>523,'materia'=>'Taller de Trabajo Final Integrador II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>524,'materia'=>'Instituciones y Regímenes de la Defensa y la Seguridad Internacional','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>525,'materia'=>'Seminario Optativo I','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>526,'materia'=>'Seminario Optativo II','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>527,'materia'=>'Seminario Optativo III','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>528,'materia'=>'Seminario Optativo IV','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>529,'materia'=>'Seminario Atlántico Sur, Malvinas y Antártida','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>530,'materia'=>'Taller de Prácticas Pre-profesionales','general'=>0,'carrera_id'=>13]);
Materia::create(['id'=>531,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>532,'materia'=>'Programación de Computadoras','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>533,'materia'=>'Organización de Computadoras','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>534,'materia'=>'Arquitectura de Computadoras','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>535,'materia'=>'Matemática 1','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>536,'materia'=>'Matemática 2','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>537,'materia'=>'Expresión de Problemas y Algoritmos','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>538,'materia'=>'Introducción al Pensamiento Científico','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>539,'materia'=>'Ingeniería de Software 1','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>540,'materia'=>'Introducción a las Bases de Datos','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>541,'materia'=>'Algoritmos y Estructuras de Datos','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>542,'materia'=>'Orientación a Objetos 1','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>543,'materia'=>'Seminario de Lenguajes','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>544,'materia'=>'Introducción a los Sistemas Operativos','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>545,'materia'=>'Matemática 3','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>546,'materia'=>'Probabilidad y Estadística','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>547,'materia'=>'Programación Concurrente','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>548,'materia'=>'Ingeniería de Software 2','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>549,'materia'=>'Orientación a Objetos 2','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>550,'materia'=>'Sistemas y organizaciones','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>551,'materia'=>'Bases de Datos 1','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>552,'materia'=>'Proyecto de Software','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>553,'materia'=>'Conceptos y Paradigmas de Lenguajes de Programación','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>554,'materia'=>'Redes y comunicaciones','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>555,'materia'=>'Ingeniería de Software 3','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>556,'materia'=>'Bases de Datos 2','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>557,'materia'=>'Fundamentos de Teoría de la Computación','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>558,'materia'=>'Sistemas Operativos','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>559,'materia'=>'Desarrollo de software en Sistemas Distribuidos','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>560,'materia'=>'Matemática Discreta','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>561,'materia'=>'Optativa Área Arquitectura, Sistemas Operativos y Redes','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>562,'materia'=>'Optativa Área Algoritmos y Lenguajes','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>563,'materia'=>'Política y Gestión Tecnológicas','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>564,'materia'=>'Aspectos Legales y Profesionales de la Informática','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>565,'materia'=>'Nuevos Escenarios','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>566,'materia'=>'Optativa Área Ingeniería de Software y Bases de Datos','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>567,'materia'=>'Seminario de Trabajo Final','general'=>0,'carrera_id'=>15]);
Materia::create(['id'=>568,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>569,'materia'=>'Matemática I','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>570,'materia'=>'Representación gráfica','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>571,'materia'=>'Historia del ferrocarril','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>572,'materia'=>'Aspectos técnicos y Socioeconómicos del Ferrocarril','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>573,'materia'=>'Matemática II','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>574,'materia'=>'Física I','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>575,'materia'=>'Introducción a la química','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>576,'materia'=>'El transporte ferroviario','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>577,'materia'=>'Tecnología ferroviaria I','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>578,'materia'=>'Matemática III','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>579,'materia'=>'Física II','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>580,'materia'=>'Tecnologías de la información y de las comunicaciones','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>581,'materia'=>'Nuevos escenarios','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>582,'materia'=>'Tecnología ferroviaria II','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>583,'materia'=>'Seguridad laboral y ambiental','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>584,'materia'=>'Legislación ferroviaria','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>585,'materia'=>'Mecánica y tecnología de los materiales','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>586,'materia'=>'Electrónica y electromecánica','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>587,'materia'=>'Tecnología ferroviaria III','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>588,'materia'=>'Termodinámica y máquinas térmicas','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>589,'materia'=>'Instalaciones eléctricas y electromecánicas','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>590,'materia'=>'Tecnología ferroviaria IV','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>591,'materia'=>'Tecnología ferroviaria V','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>592,'materia'=>'Metodología de la investigación','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>593,'materia'=>'Mecánica de los fluidos','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>594,'materia'=>'Tecnología ferroviaria VI','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>595,'materia'=>'Gestión de la calidad, ensayos y mediciones','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>596,'materia'=>'Seminario optativo','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>597,'materia'=>'Práctica supervisada ','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>598,'materia'=>'Centrales e instalaciones eléctricas','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>599,'materia'=>'Sistemas de control, automatización y señalización','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>600,'materia'=>'Material tractivo','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>601,'materia'=>'Seminario optativo','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>602,'materia'=>'Material rodante','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>603,'materia'=>'Mantenimiento y reparación en líneas electrificadas','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>604,'materia'=>'Taller de trabajo final: Proyecto de electrificación y/o electromecánico ferroviario. Práctica preprofesional ','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>605,'materia'=>'Estructuras ferroviarias','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>606,'materia'=>'Ferrourbanística','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>607,'materia'=>'Infraestructura ferroviaria I','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>608,'materia'=>'Infraestructura ferroviaria II','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>609,'materia'=>'Infraestructura ferroviaria III','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>610,'materia'=>'Seminario optativo','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>611,'materia'=>'Taller de trabajo final: proyecto de una vía férrea. Práctica preprofesional ','general'=>0,'carrera_id'=>16]);
Materia::create(['id'=>612,'materia'=>'Curso de ingreso','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>613,'materia'=>'Introducción al turismo','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>614,'materia'=>'Introducción a la geografía','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>615,'materia'=>'Estado, derecho y legislación','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>616,'materia'=>'Principios de la economía','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>617,'materia'=>'Organización y gestión de la empresa turística','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>618,'materia'=>'Introducción a la matemática','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>619,'materia'=>'Espacios turísticos de África, Asia y Oceanía','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>620,'materia'=>'Procesos históricos mundiales','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>621,'materia'=>'Servicios turísticos I','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>622,'materia'=>'Espacios turísticos de Europa','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>623,'materia'=>'Metodología de la Investigación Social','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>624,'materia'=>'Historia latinoamericana y argentina','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>625,'materia'=>'Organización y gestión hotelera','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>626,'materia'=>'Servicios turísticos II','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>627,'materia'=>'Espacios turísticos de Amércica','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>628,'materia'=>'Marketing','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>629,'materia'=>'Indicadores turísticos','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>630,'materia'=>'Historia del turismo','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>631,'materia'=>'Taller de investigación turística','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>632,'materia'=>'Espacios turísticos de Argentina','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>633,'materia'=>'Análisis económico y financiero de la actividad turística','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>634,'materia'=>'Ética profesional y responsabilidad social','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>635,'materia'=>'Taller de formulación y evaluación de proyectos','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>636,'materia'=>'Patrimonio histórico - cultural argentino','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>637,'materia'=>'Marco normativo de la actividad turística','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>638,'materia'=>'Práctica pre-profesional','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>639,'materia'=>'Inglés I','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>640,'materia'=>'Inglés II','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>641,'materia'=>'Portugués I','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>642,'materia'=>'Portugués II','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>643,'materia'=>'Informática: Módulo "Gestión de reservas"','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>644,'materia'=>'Seminario de Pensamiento Nacional y Latinoamericano','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>645,'materia'=>'Seminario de Justicia y Derechos Humanos','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>646,'materia'=>'Política turística','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>647,'materia'=>'Procesos geopolíticos de integración del turismo','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>648,'materia'=>'Diseño de productos turísticos','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>649,'materia'=>'Comportamiento organizacional y recursos humanos','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>650,'materia'=>'Turismo social y derecho al turismo','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>651,'materia'=>'Emprendedorismo','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>652,'materia'=>'Planeamiento del desarrollo turístico','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>653,'materia'=>'Cooperación internacional','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>654,'materia'=>'Taller de Trabajo Final Integrador','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>655,'materia'=>'Planeamiento y gestión del destino turístico','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>656,'materia'=>'Seminario optativo','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>657,'materia'=>'Gobernabilidad del turismo','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>658,'materia'=>'Seminario optativo','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>659,'materia'=>'Práctica pre-profesional orientada al ámbito público','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>660,'materia'=>'Inglés III','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>661,'materia'=>'Portugués III','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>662,'materia'=>'Informática: "módulo: Sistemas de Información Geográfica"','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>663,'materia'=>'Informática: "Módulo: Aplicaciones móviles"','general'=>0,'carrera_id'=>19]);
Materia::create(['id'=>664,'materia'=>'Matemática aplicada ','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>665,'materia'=>'Física aplicada','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>666,'materia'=>'Sistemas informaticos','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>667,'materia'=>'Redacción técnica','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>668,'materia'=>'Ética y deontología preofesional','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>669,'materia'=>'Comuncaciones I','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>670,'materia'=>'Electrónica y rediotécnica','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>671,'materia'=>'Administración naviera','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>672,'materia'=>'Sistemas portuarios','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>673,'materia'=>'Máquinas y sistemas asociados','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>674,'materia'=>'Primeros auxilios','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>675,'materia'=>'Actividades náuticas I','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>676,'materia'=>'Navegación I','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>677,'materia'=>'Carga y estiba I','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>678,'materia'=>'Seguridad náutica','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>679,'materia'=>'Teoría de la maniobra náutica I','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>680,'materia'=>'Derecho de la navegacón I','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>681,'materia'=>'Inglés técnico profesional I','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>682,'materia'=>'Arquitectura naval I','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>683,'materia'=>'Conocimiento de buque mercante','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>684,'materia'=>'Embarco I','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>685,'materia'=>'Probabilidad y Estadística','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>686,'materia'=>'Comuncaciones II','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>687,'materia'=>'Práctica de las nav. simulada','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>688,'materia'=>'Gestión de recursos humanos','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>689,'materia'=>'Economia naviera','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>690,'materia'=>'Administración de RR materiales','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>691,'materia'=>'Hidrografia','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>692,'materia'=>'Meteorología','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>693,'materia'=>'Actividades náuticas II','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>694,'materia'=>'Navegación electrónica','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>695,'materia'=>'Carga y estiba II','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>696,'materia'=>'Teoria de la maniobra náutica II','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>697,'materia'=>'Prevención de la contaminacion','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>698,'materia'=>'Baquía y conoc. de zona','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>699,'materia'=>'Derecho de la navegación II','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>700,'materia'=>'Inglés Técnico profesional II','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>701,'materia'=>'Arquitectura naval II','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>702,'materia'=>'Embarco II','general'=>0,'carrera_id'=>20]);
Materia::create(['id'=>90000001,'materia'=>'UNLa General','general'=>1]);
Materia::create(['id'=>90000002,'materia'=>'ENF General','general'=>1]);
    }
}
