
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: laravel
  name: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-pod
  template:
    metadata:
      labels:
        app: laravel-pod
    spec:
      containers:
      - name: laravel
        env:
        - name: DATABASE_URL
          value: mysql2://root:root@mysqldb-service:3306/shakur
        image: gonzabt3/shakur_app
        #args: ['web']
        ports:
        - containerPort: 8080
      restartPolicy: Always