
apiVersion: v1
kind: Service
metadata:
  labels:
    app: laravel
  name: laravel-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: laravel-pod
  type: ClusterIP

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: laravel-ingress
spec:
  rules:
  - host: shakur.localhost
    http:
      paths:
      - backend:
          serviceName: laravel-service
          servicePort: 8080