apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-db
  name: mysqldb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb-pod
  template:
    metadata:
      labels:
        app: mysqldb-pod
    spec:
      containers:
      - name: mysqldb
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: db-data
        image: mysql:5.7
        env:
        - name: MYSQL_DATABASE
          value: shakur
        - name: MYSQL_ROOT_PASSWORD
          value: root  
        ports:
        - containerPort: 27017
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data-pvc
      restartPolicy: Always