apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-pv
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"